##

GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjYsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzc4NTI1MjE0LCJleHAiOjE3Nzg2MTE2MTR9.IbbRkD8t843nP3pPUiG9KYUQ8axjuAUJjWW47E5EfFM

### Create user
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "name": "abcd123",
  "email": "abc@gmail.com",
  "password": "Yash@123344",
  "role": "admin"
}

### Edit users
PATCH http://localhost:3000/users/61 HTTP/1.1
Content-Type: application/json

{
    "name": "chandanS"
}

### Delete users
DELETE http://localhost:3000/users/61 HTTP/1.1


### Get Course by Query
# GET http://localhost:3000/courses?title=NestJs HTTP/1.1

### generate token
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "anil@gmail.com",
  "password": "12345678"
}